#!/bin/bash
# Shared paths/env for the xdplus build + flash scripts. Source this, don't run it.
#
# Everything here is overridable from the environment or from a local `xdplus.env`
# file (gitignored) placed next to this script. Nothing is hardcoded to one machine.
#
#   XDROOT   LineageOS 18.1 source tree root (the dir holding build/envsetup.sh)
#   XDDEV    device tree                 (default: $XDROOT/device/gpd/xdplus)
#   XDOUT    build output for xdplus     (default: $XDROOT/out/target/product/xdplus)
#   XDZIP    zip to flash                (default: newest bacon zip in $XDOUT)
#   XDKSRC   kernel source tree          (default: $XDREPO/../android_kernel_mt8176_common)

XDSCRIPTS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
XDREPO="$(dirname "$XDSCRIPTS")"
export XDSCRIPTS XDREPO

# Local, machine-specific overrides. Keep your XDROOT here instead of editing this file.
[ -f "$XDSCRIPTS/xdplus.env" ] && source "$XDSCRIPTS/xdplus.env"

: "${XDROOT:?set XDROOT to your LineageOS 18.1 source tree (see scripts/README.md)}"
export XDROOT
export XDDEV="${XDDEV:-$XDROOT/device/gpd/xdplus}"
export XDOUT="${XDOUT:-$XDROOT/out/target/product/xdplus}"
export XDKSRC="${XDKSRC:-$XDREPO/../android_kernel_mt8176_common}"

# Backup images (boot.img rollbacks, vendor partition images). Not in git — they are
# multi-hundred-MB artifacts. Probe the layouts that exist in practice: a private
# working tree that keeps them under a sibling device/backups, and a flat dir next to
# the repo. Override in xdplus.env if yours lives elsewhere.
if [ -z "${XDBACKUPS:-}" ]; then
	for _c in "$XDREPO/../../device/backups" "$XDREPO/../backups" "$XDREPO/.."; do
		[ -d "$_c" ] && XDBACKUPS="$_c" && break
	done
	unset _c
fi
export XDBACKUPS="${XDBACKUPS:-$XDREPO/..}"

# Newest bacon zip by mtime. `mka bacon` writes a fresh date-stamped name every run,
# so a hardcoded date silently reflashes a stale build. The fallback keeps this file
# sourceable before the first build exists.
if [ -z "${XDZIP:-}" ]; then
	XDZIP=$(ls -t "$XDOUT"/lineage-18.1-*-UNOFFICIAL-xdplus.zip 2>/dev/null | head -1)
	[ -z "$XDZIP" ] && XDZIP="$XDOUT/lineage-18.1-UNOFFICIAL-xdplus.zip"
fi
export XDZIP

export XDSTATE="${XDSTATE:-$XDSCRIPTS/.state}"
export XDLOG="${XDLOG:-$XDSTATE/build.log}"
export XDBOOTLOG="${XDBOOTLOG:-$XDSTATE/bootcheck.log}"
mkdir -p "$XDSTATE"

# by-name block device path. NOTE: this differs between the running system and the
# TWRP recovery kernel — recovery exposes the MMC controller under a different node.
export XDBYNAME="${XDBYNAME:-/dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name}"
export XDBYNAME_TWRP="${XDBYNAME_TWRP:-/dev/block/platform/soc/11230000.mmc/by-name}"

# Banner of a built kernel image ("Linux version 3.18.79+ (user@host) ... #N ... date").
# The banner is the ONLY reliable marker of which kernel a device is running:
# build.prop is not regenerated by every incremental build, so a freshly flashed
# image can still report the previous build's ro.build.version.incremental.
# $1 = Image.gz-dtb (or out/target/product/xdplus/kernel). Prints nothing on failure.
xdkernel_banner() {
	[ -f "$1" ] || return 1
	python3 - "$1" <<-'PY' 2>/dev/null
		import re, sys, zlib
		d = open(sys.argv[1], 'rb').read()
		i = d.find(b'\x1f\x8b\x08')
		if i < 0:
		    sys.exit(1)
		o = zlib.decompressobj(31).decompress(d[i:])
		m = re.search(rb'Linux version [^\x00]{0,160}', o)
		print(m.group().decode() if m else '', end='')
	PY
}

# Compare the in-tree-built device tree blob against the one the shipped boot.img
# carries. The MT8176 LK is unforgiving about the DTB, so this is a pre-flash gate,
# not a curiosity — it was a manual step in the out-of-tree kernel workflow and is
# kept here now that `mka bacon` builds the kernel itself.
# Prints DTB-MATCH / DTB-MISMATCH / DTB-SKIP. Returns non-zero only on a real
# mismatch; a missing reference is a skip, since the reference is a private
# artifact extracted from the stock boot.img and is not in this repo.
#
# The reference is no longer the stock DTB: as of 2026-08-10 this port changes the
# device tree deliberately, for the accelerometer mount (cust_accel@0/direction),
# so the stock blob would now report a mismatch on every build and the gate would
# stop meaning anything. The baseline is re-pinned to the current intended DTB and
# the stock one is KEPT UNTOUCHED next to it as provenance -- diff against that to
# see every deviation this port has made from what the device shipped with.
XDDTB="${XDDTB:-$XDOUT/obj/KERNEL_OBJ/arch/arm64/boot/dts/wisky8176_tb_n.dtb}"
XDDTB_REF="${XDDTB_REF:-$XDBACKUPS/kernel-prep/baseline-wisky8176_tb_n-accel-dir1-20260810.dtb}"
export XDDTB XDDTB_REF
xddtb_check() {
	if [ ! -f "$XDDTB" ]; then
		echo "DTB-SKIP: no built dtb at $XDDTB"; return 0
	fi
	if [ ! -f "$XDDTB_REF" ]; then
		echo "DTB-SKIP: no reference dtb at $XDDTB_REF (set XDDTB_REF)"; return 0
	fi
	local a b
	a=$(md5sum "$XDDTB" | awk '{print $1}')
	b=$(md5sum "$XDDTB_REF" | awk '{print $1}')
	if [ "$a" = "$b" ]; then
		echo "DTB-MATCH: $a"
		return 0
	fi
	echo "DTB-MISMATCH: built $a != shipped $b"
	return 1
}

# Optional push notification for long unattended runs. No-op unless NTFY_URL is
# set — keep the URL and token in xdplus.env (gitignored), never in a script.
# Any ntfy-compatible endpoint works; failures are swallowed on purpose, a dead
# notifier must never fail a build.
xdnotify() {
	[ -n "${NTFY_URL:-}" ] || return 0
	curl -s ${NTFY_TOKEN:+-H "Authorization: Bearer $NTFY_TOKEN"} -d "$1" "$NTFY_URL" >/dev/null 2>&1 || true
}
